tests:
  rpc_url: "https://rpc.testnet.near.org"
  private_key: "ed25519:uXN1kpbT4jWdnbdsBmh9tu15ARXzdYsYLViqdda3NaT8eHKE9y8tqRd3Hi2jU1HHXK3a91aoBR1PBTsaMFRgAbe"
  signer_private_key: "FgMzKgenWcFMMnLcPjxxxK9qNKj6gKGfxkFLrK4xvcKC"
  account_id: "napalmpapalam.testnet"
  bridge_address: "bridge_test.napalmpapalam.testnet"
  ft_address_original: "fungible_token_original.example.testnet"
  ft_address_wrapped: "fungible_token_wrapped.example.testnet"
  nft_address_original: "non_fungible_token_original.example.testnet"
  nft_address_wrapped: "non_fungible_token_wrapped.example.testnet"
  native_address_wrapped: "native_token_wrapped.example.testnet"
  feer_address: "feer_test.napalmpapalam.testnet"
  token_id: "1"
  amount: "2"
